// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: kick.proto

package kickpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqId         uint32                 `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_kick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeqId() uint32 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Envelope) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type KickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HammerType    int32                  `protobuf:"varint,1,opt,name=hammer_type,json=hammerType,proto3" json:"hammer_type,omitempty"`
	KickShrew     bool                   `protobuf:"varint,2,opt,name=kick_shrew,json=kickShrew,proto3" json:"kick_shrew,omitempty"`
	NumOfShrew    int32                  `protobuf:"varint,3,opt,name=num_of_shrew,json=numOfShrew,proto3" json:"num_of_shrew,omitempty"`
	Shrews        []*KickShrew           `protobuf:"bytes,4,rep,name=shrews,proto3" json:"shrews,omitempty"`
	ComboId       int32                  `protobuf:"varint,5,opt,name=combo_id,json=comboId,proto3" json:"combo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_kick_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{1}
}

func (x *KickRequest) GetHammerType() int32 {
	if x != nil {
		return x.HammerType
	}
	return 0
}

func (x *KickRequest) GetKickShrew() bool {
	if x != nil {
		return x.KickShrew
	}
	return false
}

func (x *KickRequest) GetNumOfShrew() int32 {
	if x != nil {
		return x.NumOfShrew
	}
	return 0
}

func (x *KickRequest) GetShrews() []*KickShrew {
	if x != nil {
		return x.Shrews
	}
	return nil
}

func (x *KickRequest) GetComboId() int32 {
	if x != nil {
		return x.ComboId
	}
	return 0
}

type KickShrew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShrewIndex    int32                  `protobuf:"varint,1,opt,name=shrew_index,json=shrewIndex,proto3" json:"shrew_index,omitempty"`
	ProtectType   int32                  `protobuf:"varint,2,opt,name=protect_type,json=protectType,proto3" json:"protect_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickShrew) Reset() {
	*x = KickShrew{}
	mi := &file_kick_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickShrew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickShrew) ProtoMessage() {}

func (x *KickShrew) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickShrew.ProtoReflect.Descriptor instead.
func (*KickShrew) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{2}
}

func (x *KickShrew) GetShrewIndex() int32 {
	if x != nil {
		return x.ShrewIndex
	}
	return 0
}

func (x *KickShrew) GetProtectType() int32 {
	if x != nil {
		return x.ProtectType
	}
	return 0
}

type KickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Money         int32                  `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	Angry         int32                  `protobuf:"varint,3,opt,name=angry,proto3" json:"angry,omitempty"`
	Power         int32                  `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
	LevelScore    int32                  `protobuf:"varint,5,opt,name=level_score,json=levelScore,proto3" json:"level_score,omitempty"`
	HammerId      int32                  `protobuf:"varint,6,opt,name=hammer_id,json=hammerId,proto3" json:"hammer_id,omitempty"`
	NumOfShrew    int32                  `protobuf:"varint,7,opt,name=num_of_shrew,json=numOfShrew,proto3" json:"num_of_shrew,omitempty"`
	ShrewResp     []*ShrewReward         `protobuf:"bytes,8,rep,name=shrew_resp,json=shrewResp,proto3" json:"shrew_resp,omitempty"`
	Combo         int32                  `protobuf:"varint,9,opt,name=combo,proto3" json:"combo,omitempty"`
	ComboId       int32                  `protobuf:"varint,10,opt,name=combo_id,json=comboId,proto3" json:"combo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickResponse) Reset() {
	*x = KickResponse{}
	mi := &file_kick_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResponse) ProtoMessage() {}

func (x *KickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResponse.ProtoReflect.Descriptor instead.
func (*KickResponse) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{3}
}

func (x *KickResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *KickResponse) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *KickResponse) GetAngry() int32 {
	if x != nil {
		return x.Angry
	}
	return 0
}

func (x *KickResponse) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *KickResponse) GetLevelScore() int32 {
	if x != nil {
		return x.LevelScore
	}
	return 0
}

func (x *KickResponse) GetHammerId() int32 {
	if x != nil {
		return x.HammerId
	}
	return 0
}

func (x *KickResponse) GetNumOfShrew() int32 {
	if x != nil {
		return x.NumOfShrew
	}
	return 0
}

func (x *KickResponse) GetShrewResp() []*ShrewReward {
	if x != nil {
		return x.ShrewResp
	}
	return nil
}

func (x *KickResponse) GetCombo() int32 {
	if x != nil {
		return x.Combo
	}
	return 0
}

func (x *KickResponse) GetComboId() int32 {
	if x != nil {
		return x.ComboId
	}
	return 0
}

type ShrewReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShrewIndex    int32                  `protobuf:"varint,1,opt,name=shrew_index,json=shrewIndex,proto3" json:"shrew_index,omitempty"`
	Reward        int32                  `protobuf:"varint,2,opt,name=reward,proto3" json:"reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShrewReward) Reset() {
	*x = ShrewReward{}
	mi := &file_kick_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShrewReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShrewReward) ProtoMessage() {}

func (x *ShrewReward) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShrewReward.ProtoReflect.Descriptor instead.
func (*ShrewReward) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{4}
}

func (x *ShrewReward) GetShrewIndex() int32 {
	if x != nil {
		return x.ShrewIndex
	}
	return 0
}

func (x *ShrewReward) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_kick_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_kick_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{6}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_kick_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{7}
}

var File_kick_proto protoreflect.FileDescriptor

var file_kick_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x69, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6b, 0x69,
	0x63, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0x52, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x0b, 0x4b, 0x69,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x6d,
	0x6d, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x68, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x69,
	0x63, 0x6b, 0x5f, 0x73, 0x68, 0x72, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x6b, 0x69, 0x63, 0x6b, 0x53, 0x68, 0x72, 0x65, 0x77, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x75, 0x6d,
	0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x68, 0x72, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x53, 0x68, 0x72, 0x65, 0x77, 0x12, 0x2a, 0x0a, 0x06, 0x73,
	0x68, 0x72, 0x65, 0x77, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x69,
	0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x53, 0x68, 0x72, 0x65, 0x77, 0x52,
	0x06, 0x73, 0x68, 0x72, 0x65, 0x77, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x62, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x62, 0x6f,
	0x49, 0x64, 0x22, 0x4f, 0x0a, 0x09, 0x4b, 0x69, 0x63, 0x6b, 0x53, 0x68, 0x72, 0x65, 0x77, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x72, 0x65, 0x77, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x68, 0x72, 0x65, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0xa8, 0x02, 0x0a, 0x0c, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x6e, 0x67, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x6e, 0x67,
	0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x6d,
	0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x61,
	0x6d, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x6f, 0x66,
	0x5f, 0x73, 0x68, 0x72, 0x65, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75,
	0x6d, 0x4f, 0x66, 0x53, 0x68, 0x72, 0x65, 0x77, 0x12, 0x33, 0x0a, 0x0a, 0x73, 0x68, 0x72, 0x65,
	0x77, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b,
	0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x72, 0x65, 0x77, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x09, 0x73, 0x68, 0x72, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6d, 0x62, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x6d, 0x62, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x62, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x62, 0x6f, 0x49, 0x64, 0x22, 0x46,
	0x0a, 0x0b, 0x53, 0x68, 0x72, 0x65, 0x77, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x68, 0x72, 0x65, 0x77, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x68, 0x72, 0x65, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x3d, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x06, 0x0a,
	0x04, 0x50, 0x6f, 0x6e, 0x67, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x66, 0x73, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x6b,
	0x69, 0x63, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kick_proto_rawDescOnce sync.Once
	file_kick_proto_rawDescData = file_kick_proto_rawDesc
)

func file_kick_proto_rawDescGZIP() []byte {
	file_kick_proto_rawDescOnce.Do(func() {
		file_kick_proto_rawDescData = protoimpl.X.CompressGZIP(file_kick_proto_rawDescData)
	})
	return file_kick_proto_rawDescData
}

var file_kick_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kick_proto_goTypes = []any{
	(*Envelope)(nil),      // 0: kick.v1.Envelope
	(*KickRequest)(nil),   // 1: kick.v1.KickRequest
	(*KickShrew)(nil),     // 2: kick.v1.KickShrew
	(*KickResponse)(nil),  // 3: kick.v1.KickResponse
	(*ShrewReward)(nil),   // 4: kick.v1.ShrewReward
	(*ErrorResponse)(nil), // 5: kick.v1.ErrorResponse
	(*Ping)(nil),          // 6: kick.v1.Ping
	(*Pong)(nil),          // 7: kick.v1.Pong
}
var file_kick_proto_depIdxs = []int32{
	2, // 0: kick.v1.KickRequest.shrews:type_name -> kick.v1.KickShrew
	4, // 1: kick.v1.KickResponse.shrew_resp:type_name -> kick.v1.ShrewReward
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kick_proto_init() }
func file_kick_proto_init() {
	if File_kick_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kick_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kick_proto_goTypes,
		DependencyIndexes: file_kick_proto_depIdxs,
		MessageInfos:      file_kick_proto_msgTypes,
	}.Build()
	File_kick_proto = out.File
	file_kick_proto_rawDesc = nil
	file_kick_proto_goTypes = nil
	file_kick_proto_depIdxs = nil
}
